name: Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  build-vite:
    runs-on: ubuntu-latest
    environment: BBJVPS

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'

      - name: Install NPM dependencies
        run: npm ci

      - name: Build assets with Vite
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vite-build
          path: public/build

  docker-build:
    runs-on: ubuntu-latest
    needs: build-vite
    environment: BBJVPS

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Vite build artifacts
        uses: actions/download-artifact@v4
        with:
          name: vite-build
          path: public/build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: disyfa/bbj-laravel:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build
    environment: BBJVPS

    steps:
      - name: Deploy on VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /var/www/app
            docker pull disyfa/bbj-laravel:latest
            docker compose up -d
